## base init and goal
start_state_x: 0.0
start_state_y: -0.25
start_state_z: 0.2
start_state_roll: 0.0
start_state_pitch: 0.0
start_state_yaw: 0.0

goal_state_x: 0.0
goal_state_y: 0.0
goal_state_z: 0.9
goal_state_roll: 0.0
goal_state_pitch: 0.0
goal_state_yaw: 0.0

## joint init and goal
start_joint1_pitch: 0.0
start_joint1_yaw: 1.57  
start_joint2_pitch: 0.0
start_joint2_yaw: 1.57
start_joint3_pitch: 0.0
start_joint3_yaw: 1.57

goal_joint1_pitch: 0
goal_joint1_yaw: 1.57
goal_joint2_pitch: 0
goal_joint2_yaw: 1.57
goal_joint3_pitch: 0
goal_joint3_yaw: 1.57

## return locaton
final_pos_x: 0.3
final_pos_y: 0.9
final_yaw: -1.57

## bound
x_low_bound: -1.0
x_high_bound: 1.0
y_low_bound: -1.0
y_high_bound: 1
z_low_bound:  0.0
z_high_bound: 1.4
pitch_joint_low_bound: -1.58
pitch_joint_high_bound: 1.58
yaw_joint_low_bound: -1.58
yaw_joint_high_bound: 1.58

# planning cost 
length_cost_thre: 6

# dist check
gimbal_roll_thresh: 1.5
gimbal_pitch_thresh: 1.0
stability_margin_thre: 0.3 # l: 0.22, s: 0.21; 
# overlap check
edf_max_tilt: 0.1 #0.18
# statics
f_max: 22.5

# continuous path
bspline_degree: 5
