######################### Grasp Form Search

link_length: 0.6 # hydrus3: 0.44 
duct_radius: 0.2 # hydrus3: 0.15 #real is + 0.9(sponge)
joint_states_pub_name: /hydrusx/joint_states
baselink: 2

# transform controller
transform_controller/baselink: fc
transform_controller/verbose: true
transform_controller/kinematic_verbose: false
transform_controller/control_verbose: false
transform_controller/f_max: 15
transform_controller/f_min: 2


####################### Grasp Motion
debug_verbose: true
object_head_direction: true
grasp_motion_planner_plugin_name: grasp_motion/whole_body

approach_delta_angle: -0.6
approach_offset_dist: 0.22 #convex: 0.22 > 0.15 * sqrt(2)

pose_fixed_count: 0.5 # convex: 1.0; cylinder: 0.5
full_contact_count: 3.0 # convex: 0.5; cylinder: 3.0

grasping_height_threshold: 0.01

contact_tilt_angle: 0.02 # convex: 0.034; cylinder: 0.02
contact_dist_threshold: 0.025 #convex: 0.03; cylinder: 0.025
contact_rolling_yaw_angle: 0.1
rolling_angle_threshold: 0.1
rolling_yaw_threshold: 0.1
default_yaw_p_gain: 110
rolling_yaw_p_gain: 1000

############################# Joint
grasp_min_torque: 150 # 150:0.2; max: 648//  cylinder: 180
grasp_max_torque: 400 # 320:0.5; max: 648    cylinder: 380
grasping_duration: 0.5
angle_control_idle_duration: 0.5
overload_check_duration: 0.1
rough_grasping_delta_angle: 0.004 #[rad/s* loop time]: 0.1 * 0.025
torque_grasping_delta_angle: 0.005
torque_grasp_threshold: 65 # 0.05 max: 648
torque_grasp_min_torque_rate: 1.0

