######################### Grasp Form Search

link_length: 0.6 # hydrus3: 0.44 
duct_radius: 0.2 # hydrus3: 0.15 #real is + 0.9(sponge)
joint_states_pub_name: /hydrusx/joint_states
baselink: 2

# transform controller
transform_controller/baselink: fc
transform_controller/verbose: true
transform_controller/kinematic_verbose: false
transform_controller/control_verbose: false
transform_controller/f_max: 15
transform_controller/f_min: 2


####################### Grasp Motion
debug_verbose: false
object_head_direction: true
grasp_motion_planner_plugin_name: grasp_motion/whole_body
approach_delta_angle: -0.45

pose_fixed_count: 1.0
grasping_height_threshold: 0.01
approach_offset_dist: 0.15
approach_acc_tilt_angle: 0.034 # 2[deg]
contact_tilt_angle: 0.03
contact_vel_threshold: 0.02
rolling_angle_threshold: 0.1
rolling_yaw_threshold: 0.1
default_yaw_p_gain: 110
rolling_yaw_p_gain: 1000

############################# Joint
grasp_min_torque: 120 # 0.2; max: 648
grasp_max_torque: 320 # 0.5; max: 648
grasping_duration: 0.5
angle_control_idle_duration: 0.5
overload_check_duration: 0.5
rough_grasping_delta_angle: 0.015
torque_grasping_delta_angle: 0.005
torque_grasp_threshold: 35 # 0.05 max: 648
torque_grasp_min_torque_rate: 1.0

